config/routes.rb
Rails.application.routes.draw do
  resources :promo_channels
  resources :gangplank_initiatives
  resources :promo_requests

  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'

  get  :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  get  :logout, to: 'sessions#destroy'

end

app/models/gangplank_initiative.rb
class GangplankInitiative < ActiveRecord::Base
end

app/controllers/gangplank_initiatives_controller.rb
class GangplankInitiativesController < ApplicationController
  before_action :set_gangplank_initiative, only: [:show, :edit, :update, :destroy]

  # GET /gangplank_initiatives
  # GET /gangplank_initiatives.json
  def index
    @gangplank_initiatives = GangplankInitiative.all
  end

  # GET /gangplank_initiatives/1
  # GET /gangplank_initiatives/1.json
  def show
  end

  # GET /gangplank_initiatives/new
  def new
    @gangplank_initiative = GangplankInitiative.new
  end

  # GET /gangplank_initiatives/1/edit
  def edit
  end

  # POST /gangplank_initiatives
  # POST /gangplank_initiatives.json
  def create
    @gangplank_initiative = GangplankInitiative.new(gangplank_initiative_params)

    respond_to do |format|
      if @gangplank_initiative.save
        format.html { redirect_to @gangplank_initiative, notice: 'Gangplank initiative was successfully created.' }
        format.json { render :show, status: :created, location: @gangplank_initiative }
      else
        format.html { render :new }
        format.json { render json: @gangplank_initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gangplank_initiatives/1
  # PATCH/PUT /gangplank_initiatives/1.json
  def update
    respond_to do |format|
      if @gangplank_initiative.update(gangplank_initiative_params)
        format.html { redirect_to @gangplank_initiative, notice: 'Gangplank initiative was successfully updated.' }
        format.json { render :show, status: :ok, location: @gangplank_initiative }
      else
        format.html { render :edit }
        format.json { render json: @gangplank_initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gangplank_initiatives/1
  # DELETE /gangplank_initiatives/1.json
  def destroy
    @gangplank_initiative.destroy
    respond_to do |format|
      format.html { redirect_to gangplank_initiatives_url, notice: 'Gangplank initiative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gangplank_initiative
      @gangplank_initiative = GangplankInitiative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gangplank_initiative_params
      params.require(:gangplank_initiative).permit(:name)
    end
end

app/helpers/gangplank_initiatives_helper.rb
module GangplankInitiativesHelper
end

app/views/gangplank_initiatives/_form.html.erb
<%= form_for(@gangplank_initiative) do |f| %>
  <% if @gangplank_initiative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gangplank_initiative.errors.count, "error") %> prohibited this gangplank_initiative from being saved:</h2>

      <ul>
      <% @gangplank_initiative.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gangplank_initiatives/edit.html.erb
<h1>Editing Gangplank Initiative</h1>

<%= render 'form' %>

<%= link_to 'Show', @gangplank_initiative %> |
<%= link_to 'Back', gangplank_initiatives_path %>

app/views/gangplank_initiatives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gangplank Initiatives</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gangplank_initiatives.each do |gangplank_initiative| %>
      <tr>
        <td><%= gangplank_initiative.name %></td>
        <td><%= link_to 'Show', gangplank_initiative %></td>
        <td><%= link_to 'Edit', edit_gangplank_initiative_path(gangplank_initiative) %></td>
        <td><%= link_to 'Destroy', gangplank_initiative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gangplank initiative', new_gangplank_initiative_path %>

app/views/gangplank_initiatives/new.html.erb
<h1>New Gangplank Initiative</h1>

<%= render 'form' %>

<%= link_to 'Back', gangplank_initiatives_path %>

app/views/gangplank_initiatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gangplank_initiative.name %>
</p>

<%= link_to 'Edit', edit_gangplank_initiative_path(@gangplank_initiative) %> |
<%= link_to 'Back', gangplank_initiatives_path %>