config/routes.rb
Rails.application.routes.draw do
  resources :promo_channels
  resources :gangplank_initiatives
  resources :promo_requests

  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'

  get  :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  get  :logout, to: 'sessions#destroy'

end

app/models/promo_channel.rb
class PromoChannel < ActiveRecord::Base
end

app/controllers/promo_channels_controller.rb
class PromoChannelsController < ApplicationController
  before_action :set_promo_channel, only: [:show, :edit, :update, :destroy]

  # GET /promo_channels
  # GET /promo_channels.json
  def index
    @promo_channels = PromoChannel.all
  end

  # GET /promo_channels/1
  # GET /promo_channels/1.json
  def show
  end

  # GET /promo_channels/new
  def new
    @promo_channel = PromoChannel.new
  end

  # GET /promo_channels/1/edit
  def edit
  end

  # POST /promo_channels
  # POST /promo_channels.json
  def create
    @promo_channel = PromoChannel.new(promo_channel_params)

    respond_to do |format|
      if @promo_channel.save
        format.html { redirect_to @promo_channel, notice: 'Promo channel was successfully created.' }
        format.json { render :show, status: :created, location: @promo_channel }
      else
        format.html { render :new }
        format.json { render json: @promo_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promo_channels/1
  # PATCH/PUT /promo_channels/1.json
  def update
    respond_to do |format|
      if @promo_channel.update(promo_channel_params)
        format.html { redirect_to @promo_channel, notice: 'Promo channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo_channel }
      else
        format.html { render :edit }
        format.json { render json: @promo_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promo_channels/1
  # DELETE /promo_channels/1.json
  def destroy
    @promo_channel.destroy
    respond_to do |format|
      format.html { redirect_to promo_channels_url, notice: 'Promo channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo_channel
      @promo_channel = PromoChannel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_channel_params
      params.require(:promo_channel).permit(:name)
    end
end

app/helpers/promo_channels_helper.rb
module PromoChannelsHelper
end

app/views/promo_channels/_form.html.erb
<%= form_for(@promo_channel) do |f| %>
  <% if @promo_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promo_channel.errors.count, "error") %> prohibited this promo_channel from being saved:</h2>

      <ul>
      <% @promo_channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promo_channels/edit.html.erb
<h1>Editing Promo Channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @promo_channel %> |
<%= link_to 'Back', promo_channels_path %>

app/views/promo_channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Promo Channels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promo_channels.each do |promo_channel| %>
      <tr>
        <td><%= promo_channel.name %></td>
        <td><%= link_to 'Show', promo_channel %></td>
        <td><%= link_to 'Edit', edit_promo_channel_path(promo_channel) %></td>
        <td><%= link_to 'Destroy', promo_channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promo channel', new_promo_channel_path %>

app/views/promo_channels/new.html.erb
<h1>New Promo Channel</h1>

<%= render 'form' %>

<%= link_to 'Back', promo_channels_path %>

app/views/promo_channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @promo_channel.name %>
</p>

<%= link_to 'Edit', edit_promo_channel_path(@promo_channel) %> |
<%= link_to 'Back', promo_channels_path %>