config/routes.rb
Rails.application.routes.draw do
  resources :promo_channels
  resources :gangplank_initiatives
  resources :promo_requests

  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'

  get  :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  get  :logout, to: 'sessions#destroy'

end

app/models/promo_request.rb
class PromoRequest < ActiveRecord::Base
  has_many :promo_channel_promo_requests
  has_many :promo_channels, through: :promo_channel_promo_requests
  belongs_to :gangplank_location
  belongs_to :gangplank_initiative

  validates_presence_of :event_name, :gangplank_initiative, :gangplank_location, :organizer_name, :organizer_email, :event_privacy

end

app/controllers/promo_requests_controller.rb
class PromoRequestsController < ApplicationController
  before_action :set_promo_request, only: [:show, :edit, :update, :destroy]
  
  # GET /promo_requests
  # GET /promo_requests.json
  def index
    @promo_requests = PromoRequest.all
  end

  # GET /promo_requests/1
  # GET /promo_requests/1.json
  def show
    @gangplank_location = GangplankLocation.find(@promo_request.gangplank_location_id)
    @gangplank_initiative = GangplankInitiative.find(@promo_request.gangplank_initiative_id)
  end

  # GET /promo_requests/new
  def new
    @gangplank_locations = GangplankLocation.all
    @gangplank_initiatives = GangplankInitiative.all
    @promo_request = PromoRequest.new
  end

  # GET /promo_requests/1/edit
  def edit
    @gangplank_locations = GangplankLocation.all
    @gangplank_initiatives = GangplankInitiative.all
  end

  # POST /promo_requests
  # POST /promo_requests.json
  def create
    @promo_request = PromoRequest.new(promo_request_params)

    respond_to do |format|
      if @promo_request.save
        format.html { redirect_to @promo_request, notice: 'Promo request was successfully created.' }
        format.json { render :show, status: :created, location: @promo_request }
      else
        format.html { render :new }
        format.json { render json: @promo_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promo_requests/1
  # PATCH/PUT /promo_requests/1.json
  def update
    respond_to do |format|
      if @promo_request.update(promo_request_params)
        format.html { redirect_to @promo_request, notice: 'Promo request was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo_request }
      else
        format.html { render :edit }
        format.json { render json: @promo_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promo_requests/1
  # DELETE /promo_requests/1.json
  def destroy
    @promo_request.destroy
    respond_to do |format|
      format.html { redirect_to promo_requests_url, notice: 'Promo request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo_request
      @promo_request = PromoRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_request_params
      params.require(:promo_request).permit(:event_name, :description, :start_datetime, :end_datetime, :gangplank_location_id, :promo_image_uri, :gangplank_initiative_id, :organizer_name, :organizer_email, :is_space_reserved, :event_privacy, :is_free, :registration_url, :press_release_uri, promo_channel_ids: [])
    end
end

app/helpers/promo_requests_helper.rb
module PromoRequestsHelper
end

app/views/promo_requests/_form.html.erb
<%= form_for(@promo_request) do |f| %>
  <% if @promo_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promo_request.errors.count, "error") %> prohibited this promo_request from being saved:</h2>

      <ul>
      <% @promo_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_name %><br>
    <%= f.text_field :event_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_datetime %><br>
    <%= f.datetime_field :start_datetime %>
  </div>
  <div class="field">
    <%= f.label :end_datetime %><br>
    <%= f.datetime_field :end_datetime %>
  </div>
  <div class="field">
    <%= f.label :gangplank_location_id %><br>
    <%= f.collection_select(:gangplank_location_id, @gangplank_locations, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :promo_image_uri %><br>
    <%= f.text_field :promo_image_uri %>
  </div>
  <div class="field">
    <%= f.label :gangplank_initiative_id %><br>
    <%= f.collection_select(:gangplank_initiative_id, @gangplank_initiatives, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :organizer_name %><br>
    <%= f.text_field :organizer_name %>
  </div>
  <div class="field">
    <%= f.label :organizer_email %><br>
    <%= f.text_field :organizer_email %>
  </div>
  <div class="field">
    <%= f.label :is_space_reserved %><br>
    <%= f.check_box :is_space_reserved %>
  </div>
  <div class="field">
    <%= f.label :event_privacy %><br>
    <%= f.select(:event_privacy, options_for_select([['Open/public', 'open'], ['Closed/private', 'closed']])) %>
  </div>
  <div class="field">
    <%= f.label :is_free %><br>
    <%= f.check_box :is_free %>
  </div>
  <div class="field">
    <%= f.label :registration_url %><br>
    <%= f.text_field :registration_url %>
  </div>
  <div class="field">
    <%= f.label 'Promotion Channels' %>
    <div>
    <% PromoChannel.all.each do |promo_channel| %>
       <label>
          <%= check_box_tag "promo_request[promo_channel_ids][]", promo_channel.id, f.object.promo_channels.include?(promo_channel) %>
          <%= promo_channel.name %>
       </label>
    <% end %>
    </div>
  </div>
  <div class="field">
    <%= f.label :press_release_uri %><br>
    <%= f.text_field :press_release_uri %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promo_requests/edit.html.erb
<h1>Editing Promo Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @promo_request %> |
<%= link_to 'Back', promo_requests_path %>

app/views/promo_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Promo Requests</h1>

<table>
  <thead>
    <tr>
      <th>Event name</th>
      <th>Location</th>
      <th>Initiative</th>
      <th>Organizer Name</th>
      <th>Space Reserved?</th>
      <th>Event Privacy</th>
      <th>Event Free?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promo_requests.each do |promo_request| %>
      <tr>
        <td><%= promo_request.event_name %></td>
        <td><%= promo_request.gangplank_location.name %></td>
        <td><%= promo_request.gangplank_initiative.name %></td>
        <td><%= promo_request.organizer_name %></td>
        <td><%= promo_request.is_space_reserved %></td>
        <td><%= promo_request.event_privacy %></td>
        <td><%= promo_request.is_free %></td>
        <td><%= link_to 'Show', promo_request %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promo request', new_promo_request_path %>

app/views/promo_requests/new.html.erb
<h1>New Promo Request</h1>

<%= render 'form' %>

<%= link_to 'Back', promo_requests_path %>

app/views/promo_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= @promo_request.event_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @promo_request.description %>
</p>

<p>
  <strong>Start:</strong>
  <%= @promo_request.start_datetime %>
</p>

<p>
  <strong>End:</strong>
  <%= @promo_request.end_datetime %>
</p>

<p>
  <strong>Location:</strong>
  <%= @gangplank_location.name %>
</p>

<p>
  <strong>Promo image uri:</strong>
  <%= @promo_request.promo_image_uri %>
</p>

<p>
  <strong>Initiative:</strong>
  <%= @gangplank_initiative.name %>
</p>

<p>
  <strong>Organizer name:</strong>
  <%= @promo_request.organizer_name %>
</p>

<p>
  <strong>Organizer email:</strong>
  <%= @promo_request.organizer_email %>
</p>

<p>
  <strong>Is space reserved:</strong>
  <%= @promo_request.is_space_reserved %>
</p>

<p>
  <strong>Event privacy:</strong>
  <%= @promo_request.event_privacy %>
</p>

<p>
  <strong>Is free:</strong>
  <%= @promo_request.is_free %>
</p>

<p>
  <strong>Registration url:</strong>
  <%= @promo_request.registration_url %>
</p>

<p>
  <strong>Press release uri:</strong>
  <%= @promo_request.press_release_uri %>
</p>

<p>
  <strong>Channels</strong>
  <ul>
    <% @promo_request.promo_channels.each do |promo_channel| %>
       <li>
          <%= promo_channel.name %>
       </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_promo_request_path(@promo_request) %> |
<%= link_to 'Back', promo_requests_path %>